name: Build Client Image

on:
  push:
    branches: [build/test]
    # paths:
    #   - "client/**"

env:
  # VERSION_TYPE: patch # major, minor, patch
  # VERSION_STATE: alpha # alpha, beta, rc
  CLIENT_GHCR_IMAGE: ghcr.io/teamgrit-lab/cobiz-client

jobs:
  deploy:
    runs-on: [self-hosted, label-moodTracker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: check location
        run: pwd

      - name: Copy Project
        run: cp -rf ../MoodTracker ../../../../.

      - name: check my location
        run: cd ../../../../MoodTracker/client && ls -al

      - name: Client build
        run: cd ../../../../MoodTracker/client && yarn && yarn build

      - name: Set execute permission for gradlew
        run: cd ../../../../MoodTracker/client/server && chmod +x ./gradlew

      - name: Build with Gradle
        run: cd ../../../../MoodTracker/client/server && ./gradlew build

      - name: Run application in background
        run: cd ../../../../MoodTracker/client/server && nohup java -jar build/libs/moodTracker-0.0.1-SNAPSHOT.jar &
