name: Build Client Image

on:
  push:
    branches: [build/test]
    # paths:
    #   - "client/**"

env:
  # VERSION_TYPE: patch # major, minor, patch
  # VERSION_STATE: alpha # alpha, beta, rc
  CLIENT_GHCR_IMAGE: ghcr.io/teamgrit-lab/cobiz-client

jobs:
  deploy:
    runs-on: [self-hosted, label-moodTracker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: check location
        run: pwd

      - name: check my location
        run: ls -al

      # - name: Copy Project
      #   run: cp -f ./_work/MoodTracker/MoodTracker ../../.

      # - name: Set execute permission for gradlew
      #   run: chmod +x ./gradlew

      # - name: Build with Gradle
      #   run: ./gradlew build

      # - name: Run application in background
      #   run: nohup java -jar build/libs/moodTracker-0.0.1-SNAPSHOT.jar &
